### ISSUE TITLE
Provide an escape hatch to mix-in "normal" Playwright steps

### ISSUE THREAD

**Issue by michaelfromyeg** [browserbase/stagehand#204]
For some of the work I'm doing, I only need LLM help at certain steps, but most of the time can get away with normal `playwright` commands. Not sure if this is already supported, but ideally there'd be an easy escape hatch for developers to mix-in normal / non-LLM playwright commands at certain stages of the pipeline.

(e.g., I go to the page, I know I have to click the login button first and that's available with a specific classname, but then I need the LLM to do some guesswork around choosing a product to buy)

**Comment by pkiv** [comment]
Hey @michaelfromyeg! Thanks for the issue. I do this sometimes in my scripts too. We do expose the playwright `page` and `context` objects on stagehand for you to use as an escape hatch. 

```
  await stagehand.page.goto("https://example.com");
  await stagehand.act({ action: "Click the 'All Case Records Search' link" });
  await stagehand.page.locator("label").filter({ hasText: "Search By" }).click();
  ```

**Comment by michaelfromyeg** [comment]
ah nice thank you - new to playwright so didn't realize those were the direct objects

(also thank you for the quick reply!)
