### ISSUE TITLE
remove unneeded markup in DOM elements

### ISSUE THREAD

**Issue by jeremypress** [browserbase/stagehand#40]
Currently we don't strip anything from our candidate elements, and surely there are a lot of attributes that we don't need for LLM context that are wasting tokens. To get started, turn on DOM debugging and inspect the console of the playwright window to see what elements we are pulling out and what attributes we can systematically ignore

**Comment by filip-michalsky** [comment]
This has been done, but we will continue to monitor to see if we can make it better!
