### ISSUE TITLE
Decouple Stagehand from OpenAI

### ISSUE THREAD

**Issue by pkiv** [browserbase/stagehand#52]
Developers should be able to bring different models to Stagehand. Maybe even across different functions of Stagehand! (ie: claude 3.5 for playwright codegen but 4o for data extraction?)

**Comment by filip-michalsky** [comment]
this is also related to:
a) Abstract Model Name into an env var
and/or
b) use an LLM router like litellm (but could intro a dependency) https://github.com/BerriAI/litellm

**Comment by filip-michalsky** [comment]
#56
