### ISSUE TITLE
Fix CI Evals with banalyzer

### ISSUE THREAD

**Issue by filip-michalsky** [browserbase/stagehand#88]
Need to update CI.yml file most likely:

Run pnpm evals

> stagehand@1.0.0 evals /home/runner/work/stagehand/stagehand
> pnpm build-dom-scripts && npx braintrust eval evals/index.eval.ts

> stagehand@1.0.0 build-dom-scripts /home/runner/work/stagehand/stagehand
> mkdir -p ./lib/dom/build && mkdir -p ./dist/dom/build && esbuild ./lib/dom/*.ts --bundle --outdir=./dist/dom/build

  dist/dom/build/process.js  8.6kb
  dist/dom/build/debug.js    4.2kb
  dist/dom/build/utils.js    535b 
  dist/dom/build/types.js     [15](https://github.com/browserbase/stagehand/actions/runs/11153382987/job/31000767285#step:7:16)b 

⚡ Done in 5ms
Failed to compile /home/runner/work/stagehand/stagehand/evals/index.eval.ts: ENOENT: no such file or directory, open '/home/runner/work/stagehand/stagehand/evals/bananalyzer-ts/static/examples.json'
Processing 0 evaluators...

**Comment by navidkpr** [comment]
Done!
